// <auto-generated />
using System;
using CertificateService.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CertificateService.Infrastructure.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260829032615_CreateTables")]
    partial class CreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CertificateService.Domain.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CertificateType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredentialId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IssuerDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MediaProjectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationUrl")
                        .HasColumnType("text");

                    b.Property<int?>("WorkLoadHours")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MediaProjectionId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("CertificateService.Domain.Entities.CertificatePost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.ToTable("CertificatePosts");
                });

            modelBuilder.Entity("CertificateService.Domain.Entities.LanguageProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LanguageProjections");
                });

            modelBuilder.Entity("CertificateService.Domain.Entities.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CommittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCommitted")
                        .HasColumnType("boolean");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("CertificateService.Domain.Entities.MediaProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Url", "MediaId")
                        .IsUnique();

                    b.ToTable("MediaProjections");
                });

            modelBuilder.Entity("CertificateService.Domain.Entities.PostContentProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PostProjectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PostProjectionId");

                    b.ToTable("PostContentProjections");
                });

            modelBuilder.Entity("CertificateService.Domain.Entities.PostProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uuid");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("MediaProjectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("MediaProjectionId");

                    b.ToTable("PostProjections");
                });

            modelBuilder.Entity("CertificateService.Domain.Entities.Certificate", b =>
                {
                    b.HasOne("CertificateService.Domain.Entities.MediaProjection", "MediaProjection")
                        .WithMany()
                        .HasForeignKey("MediaProjectionId");

                    b.Navigation("MediaProjection");
                });

            modelBuilder.Entity("CertificateService.Domain.Entities.CertificatePost", b =>
                {
                    b.HasOne("CertificateService.Domain.Entities.Certificate", "certificate")
                        .WithMany()
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("certificate");
                });

            modelBuilder.Entity("CertificateService.Domain.Entities.PostContentProjection", b =>
                {
                    b.HasOne("CertificateService.Domain.Entities.LanguageProjection", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CertificateService.Domain.Entities.PostProjection", null)
                        .WithMany("PostContents")
                        .HasForeignKey("PostProjectionId");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("CertificateService.Domain.Entities.PostProjection", b =>
                {
                    b.HasOne("CertificateService.Domain.Entities.Certificate", "Certificate")
                        .WithMany("PostProjections")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CertificateService.Domain.Entities.MediaProjection", "MediaProjection")
                        .WithMany()
                        .HasForeignKey("MediaProjectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");

                    b.Navigation("MediaProjection");
                });

            modelBuilder.Entity("CertificateService.Domain.Entities.Certificate", b =>
                {
                    b.Navigation("PostProjections");
                });

            modelBuilder.Entity("CertificateService.Domain.Entities.PostProjection", b =>
                {
                    b.Navigation("PostContents");
                });
#pragma warning restore 612, 618
        }
    }
}
