name: Manual Workflow

on:
  workflow_dispatch:
jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v2
      - name: Run teste
        run: env
