name: Manual Workflow

on:
  workflow_dispatch:
jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v2
      - name: Run teste
        run:
          echo "Em execução ${{ secrets.REACT_APP_KEY }}"
