name: Manual Workflow

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
         - name: Checkout
           uses: actions/checkout@v1
         - name: Build
           run: |
                npm install
                npm run-script build
           env:
                REACT_APP_APIKey: ${{ secrets.REACT_APP_KEY }}
                REACT_APP_APISecret: ${{ secrets.REACT_APP_SERVICEID }}
           
